CREATE TABLE [dbo].[Game]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Code] NVARCHAR(50) NOT NULL,
	[Name] NVARCHAR(100) NOT NULL,
	[BoardData] NVARCHAR(MAX) NOT NULL,
	[CreatedDate] DATETIME2 NOT NULL
)
